### ISSUE TITLE
Terms Question: Should we be translating React terms such as "props", "state", and "lifecycle"?

### ISSUE THREAD

**Issue by GasimGasimzada** [reactjs/az.reactjs.org#11]
I am asking this because, currently I have translated these values and as I read through them, it makes it harder to catch the actual name of it. My suggestion it to keep singular values and add azerbaijani suffixes:

- prop and prop**lar**
- state and **state-li komponent** (stateful component)
- lifecycle **metodları** (lifecycle methods)

What do you guys think? In documentation and tutorial, we are already explaining what they are in Azerbaijani using simpler terms. So, I think explaining them in Azerbaijani while making people remember the naming this way would make future conversations easier in React community.

**Comment by Haqverdi** [comment]
I absolutely agree, such use of these keywords I think will be easier to understand

**Comment by GasimGasimzada** [comment]
I have updated the glossary for state and props as I have been experimenting with these words locally while translating and props and state are definitely the right way to go about this. If these words are being used in React's context, we should use the ones shown above. If these words are used in general context, you should use the actual translation, which I have also added to the glossary.
