### ISSUE TITLE
Translation of the term "Classes"

### ISSUE THREAD

**Issue by GasimGasimzada** [reactjs/az.reactjs.org#163]
This issue is created to discuss if we should be using "siniflər", "class-lar", or "klaslar"? Currently, we have been using "klaslar" to refer to classes; however, this might not be the best option. I want to hear your opinions.

*Comments in Azerbaijani are more than welcome!*

**Comment by Maharramoff** [comment]
Let me give a simple example, though there are certainly more.  If we look at [Wikipedia](https://tr.wikipedia.org/wiki/S%C4%B1n%C4%B1f_(programlama)), we see that everyone wrote this word in their own language. Why should we keep this in English?

**Comment by Maharramoff** [comment]
And I also propose replacing the word "uşaq komponent|element|sinif" respectively with "alt (or "törəmə") komponent|element|sinif" etc.

**Comment by GasimGasimzada** [comment]
Fair point, let's do it. I checked it out for other languages and they all translated the terms.

Regarding "uşaq komponent|element|sinif", "alt" or törəmə is better. But in most cases uşaq komponent (or element) refers to child component (or element) in React, which actually refers to child nodes in the component tree. So, we need to be careful what we translate. If we translate the term "child class inherited from X" or "subclass", we can do it. But if we translate something like "render child element in component X," it is not alt (or törəmə) anymore. Even from the technically, it refers to composition vs inheritance.

**Comment by GasimGasimzada** [comment]
#165

**Comment by GasimGasimzada** [comment]
Closing it now as major part of this has been done. If there are any other issues in the future, just create a new PR with the fixes!
