### ISSUE TITLE
"Runtime" Translation in Azerbaijani

### ISSUE THREAD

**Issue by azizaismayilova** [reactjs/az.reactjs.org#17]
Should we translate "runtime" in Azerbaijani as "icra vaxtı" or keep it in the English version?

**Comment by Haqverdi** [comment]
in my opinion, should indicate both, example: icra vaxti (runtime)

**Comment by GasimGasimzada** [comment]
Writing both doesn't sound good when it is being used across the entire documentation. That means if a page has this written 10 times, we are going to need to write it 10 times. We should generally try to avoid writing these kinds of methods unless absolutely necessary (e.g if the documentation itself explains the meaning of these words).

**Comment by azizaismayilova** [comment]
The used example of "runtime" is like this: Bizim React applikasiyalarımız runtime müddətində davamlı şəkildə HTML DOM-u modifikasi edir.

I agree that we should use only one version and add the explanation in the glossary.

**Comment by GasimGasimzada** [comment]
@azizaismayilova what about "işləmə müddətində"?

**Comment by GasimGasimzada** [comment]
@Haqverdi I want to get back to you on what meant by showing an example from the text. Currently, I am translating a section regarding Immutability. I think the translation of immutability is "Dəyişməzlik." In this section, there is a paragraph that introduces immutability. So, just to give readers an idea on what it is in English, I wrote the English version in parenthesis **only once**:

> Bu bölmədə biz dəyişməzlik (immutability) və dəyişməzliyi öyrenməyin niyə vacib olduğunu müzakirə edəcəyik.

**Comment by azizaismayilova** [comment]
@GasimGasimzada For me, "icra vaxtı" and "işləmə müddəti" have the same meaning. We can use "icra müddəti", it sounds better than both of them.

**Comment by GasimGasimzada** [comment]
okay!
