### ISSUE TITLE
Glossary of Terms

### ISSUE THREAD

**Issue by GasimGasimzada** [reactjs/az.reactjs.org#2]
### THIS PAGE WILL NO LONGER BE UPDATED. GLOSSARY IS NOW MOVED TO ITS [OWN FILE](https://github.com/reactjs/az.reactjs.org/blob/master/glossary.md ) IF YOU WANT TO MAKE CHANGES TO THIS FILE, FORK THE REPO, EDIT [glossary.md](https://github.com/reactjs/az.reactjs.org/blob/master/glossary.md) FILE, AND CREATE A PR WITH THE EXPLANATION FOR THE CHANGE / ADDITION.

# Glossary of Terms

## How to use React with suffixes?

- React-i
- React-ə
- React ilə
- React-lə
- React-də

# How to use API with suffixes?

I think it makes more sense to keep API as it is pronounced in English: https://www.youtube.com/watch?v=gZTn6AQDy1g

So, we should use suffixes like this:

- API-ı
- API-a
- API ilə
- API-la
- API-da

*Also make sure to write API, not APİ*

## React Terms

| English | Azərbaycanca |
| :---: | :---:|
| class component | klas komponent |
| controlled component | kontrol olunan komponent |
| click | tıklamaq |
| context | 
| component | komponent |
| fragments | fraqmentlər |
| functional component | funskional komponent |
| portal | portal |
| properties | parametrlər |
| prop(s) | prop(lar) |
| lifecycle | lifecycle |
| ref | ref |
| render | render etmək | 
| state<br />(in context of React components) | state |
| state<br />(in general context) | vəziyyət | 
| stateful component | state-li komponent |
| uncontrolled component | kontrolsuz komponent |

## Other Terms

| English | Azərbaycanca |
| :---: | :---:|
| accessibility | imkanlılıq |
| anchor | anker təqi |
| application | applikasiya |
| array | massiv |
| arrow function | arrow funkiyası |
| asynchronous | asinxron |
| attributes | atributlar |
| bug | baq |
| bundle | paket |
| callback | | 
| child | uşaq |
| class | klas |
| composition | kompozisiya |
| conditional rendering | şərtli render |
| constructor | konstuktor |
| crash | çökmə |
| current | cari |
| data | məlumat |
| debug | dibaq |
| declarative | deklarativ |
| DOM | DOM |
| elements | elementlər |
| embedding expressions | |
| expression | ifadə |
| external plugins | xarici pluginlər  |
| extent | genişləndirmək  |
| extention | genişlənmə  |
| event handler | hadisə işləyicisi  |
| example | nümunə |
| framework | freymvork |
| guide | təlimat |
| hierarchy | ierarxiya |
| higher order function | yüksək dərəcəli funskiya |
| immutability | dəyişməzlik |
| imperative | imperativ |
| implementation | tətbiq |
| import | import |
| inheritance | varislik |
| initialize | inisializasiya |
| instance | instansiya (computer term) |
| interact | qarşılıqlı təsir etmək |
| item | element |
| keyboard | klaviatur |
| library | kitabxana |
| local | lokal |
| map | uzlaşdırmaq |
| maintainer | saxlayıcı |
| mock |  |
| nested | |
| node | nod |
| note | qeyd |
| operator | operator |
| output | nəticə |
| package | paket |
| parent | valideyn |
| pattern | pattern |
| plain | sadə |
| polyfill | polifil |
| pooling | pulinq |
| power | dəstəkləmək |
| private | privat |
| propagate | yaymaq |
| refactor | refaktor |
| reference | referans |
| reset | sıfırlamaq |
| reuse | təkrar istifadə |
| runtime | icra müddəti |
| stack | stek |
| syntax | sintaksis |
| technology stack | texnologiya steki |
| tip | məsləhət |
| Tick |
| tool | alət |
| tutorial | dərslik |
| UI | UI (not Azerbaijani İ) |
| user | istifadəçi |
| Web | Veb |
| wrapped component | əhatə olan komponent |
| native | nativ |

**Comment by Haqverdi** [comment]
xaxaxa)) very interesting translations, but somewhere i will change it

**Comment by GasimGasimzada** [comment]
https://github.com/reactjs/az.reactjs.org/issues

**Comment by GasimGasimzada** [comment]
Add "parent" translation and split react terms from general dev terms

**Comment by GasimGasimzada** [comment]
Add constructor and initialization translations

**Comment by azizaismayilova** [comment]
- Add "anchor" translation

**Comment by Haqverdi** [comment]
- translate 'package'

**Comment by GasimGasimzada** [comment]
Update props and state translation

**Comment by azizaismayilova** [comment]
Add "reset" translation

**Comment by GasimGasimzada** [comment]
- Translate "crash"

**Comment by GasimGasimzada** [comment]
Does anyone here agree that immutable = dəyişməzlik? I have added it to the glossary and currently using it. If someone does not think that this is the correct word, write here so we can discuss it.

**Comment by azizaismayilova** [comment]
- Add "wrapped component" translation

**Comment by azizaismayilova** [comment]
- Add "runtime" translation

**Comment by Haqverdi** [comment]
- add conditional rendering translation
- update "immutable" translation
in my opinion immutable translation correct way is 'dəyişməyən'

**Comment by GasimGasimzada** [comment]
I wrote the wrong translation. I am talking about immutability, not immutable.

**Comment by Haqverdi** [comment]
ok, then i think most suitable variant dəyişməzlik or dəyişilməzlik

**Comment by azizaismayilova** [comment]
- Add "interact" translation

**Comment by GasimGasimzada** [comment]
- Translate bundle and import

**Comment by Haqverdi** [comment]
"Take the Tutorial" translated as "Dərsiliyi Götür", I think it would be better for understanding translate this to "Dərsliyə başla", and since now a literal translation is being made and it does not look very good

**Comment by azizaismayilova** [comment]
add "maintainer" translation

**Comment by azizaismayilova** [comment]
- Add "output" translation

**Comment by azizaismayilova** [comment]
- add "pattern" translation

**Comment by azizaismayilova** [comment]
- add "instance" translation

**Comment by Haqverdi** [comment]
- add "native" translation

**Comment by saidfagan** [comment]
how to translate "local state"? "lokal state" or "daxili state"? or, perhaps "yerli state"?

**Comment by saidfagan** [comment]
and what about _to inherit_? _genişləndirmək_ or _varis olmaq_?

**Comment by saidfagan** [comment]
translation for _arrow function_, _ox funksiyasi_?

**Comment by GasimGasimzada** [comment]
For arrow function, I wrote arrow funskiyasi because I think ox funskiyasi is not very clear when someone reads through the content.

Inherit is written under “inheritance” in the glossary— varislik. Genishlendirmek is extend.

Are you talking about React state or just rhe technical word. When using React state, I use “state” but when the used context is not about React’s state, I use “veziyyet.” React’s state is kind of like special noun.

Yerli in computer terms is confusing. Daxili = internal. I write it as “lokal” because it is immediately clear to the reader.

For words that do not have clear translations, I try to use azerbaijani words that are commonly used among azerbaijani developers (checking forums and stuff).

**Comment by saidfagan** [comment]
Thanks for the answer. So let's summarize.
arrow function - arrow funksiyası
inheritance - varislik
local state - lokal state
But how about the verb _to inherit_? _varis olmaq_ does not match properly. In Java, for example, they use the keyword _extends_ when class inherits another class. So I suggest using _genişləndirmək_ for _to inherit_.
By the way ,the State and Lifecycle section is ready. Tomorrow I will recheck it and create a pull request.

**Comment by GasimGasimzada** [comment]
Okay, then let's use genişləndirmək for "inherit." Otherwise, yes agreed.

> Tomorrow I will recheck it and create a pull request.

Great! :)

**Comment by GasimGasimzada** [comment]
- Add Asynchronous
- Add Imperative
- Add suffixes and pronunciation for API

**Comment by GasimGasimzada** [comment]
Add node

**Comment by saidfagan** [comment]
Why not to use "düyün" for "node"?

**Comment by GasimGasimzada** [comment]
@saidfagan Is this word being used in Azerbaijani translation of the computer term "node"? I personally chose "nod" because I thought there is no actual translation of this word. I just checked the word for it in Azerbaijan English Computer Dictionary: http://enaz.online/index.php?id=5531 (node), http://enaz.online/index.php?id=6174 (parent node). We can change them to "qovşaq" but as far as I knew, this word means Junction -- The act or process of joining or the condition of being joined.

The translations for this word is ambiguous at best. Therefore, I created a poll here; so that, we can decide on what to use: https://www.strawpoll.me/17766391.

@Haqverdi, @azizaismayilova, @saidfagan, please vote so that we can decide how to move with this word.

**Comment by GasimGasimzada** [comment]
Add "higher order component" translation.

**Comment by saidfagan** [comment]
@GasimGasimzada I've never seen this word translated as "düyün", too. Programming related literature is very scarce in Azerbaijani. I just think this translation suits best.
Voted, waiting for the results.

**Comment by saidfagan** [comment]
So _event handler_ will be _hadisə işləyicisi_. But, how will _to handle events_ be? I think _hadisə emal etmək_ suits best.

**Comment by saidfagan** [comment]
add translation for _default_

**Comment by saidfagan** [comment]
add translation for _bind_ and _binding_

**Comment by saidfagan** [comment]
add translation for _field_, like class field

**Comment by GasimGasimzada** [comment]
> So _event handler_ will be _hadisə işləyicisi_. But, how will _to handle events_ be? I think _hadisə emal etmək_ suits best.

Its okay. Regarding other translations, where did you add them/

**Comment by saidfagan** [comment]
I am currently working on Handling Events chapter. All of this words are from that chapter.

**Comment by GasimGasimzada** [comment]
Could you please write the translations, so I can add them?

**Comment by saidfagan** [comment]
I suggest:
default - ilkin
bind - bağlamaq
binding - bağlantı
class field - klas sahəsi
Not sure about all of these. Will be glad to hear better translations.

**Comment by saidfagan** [comment]
Any ideas about _loop_? _dövr_, perhaps?

**Comment by GasimGasimzada** [comment]
Add pooling translation.

**Comment by GasimGasimzada** [comment]
Add controlled and uncontrolled component translation
