### ISSUE TITLE
Translation of "pattern"

### ISSUE THREAD

**Issue by azizaismayilova** [reactjs/az.reactjs.org#20]
Should we keep "pattern" in English or we can translate it as "şablon" in Azerbaijani and add to the Glossary in any case.

**Comment by GasimGasimzada** [comment]
I think you should keep it as "pattern" or maybe "patterna" that many people use in our country for this explanation. "Şablon" is generally considered as template, not as pattern. I do not believe someone will understand the meaning of the text if we use Şablon.
