### ISSUE TITLE
New merge changes

### ISSUE THREAD

**Issue by GasimGasimzada** [reactjs/az.reactjs.org#31]
- [x] Check the test in Code Splitting -- line 86-91 (@GasimGasimzada)
- [x] Make sure accessibility links are correct  --https://github.com/reactjs/az.reactjs.org/pull/30/commits/ccce496d72863c9beba985cdca3ff7164b333015#diff-dac5eb061260201bf8207cee2ee7d273 (@azizaismayilova)
- [x] Change link URLs from HTTP to HTTPS in "Introduction to JSX" -- line 73, 141, 184 (@Haqverdi)

**Comment by GasimGasimzada** [comment]
NOTE: All the changes from the latest pull request are regarding links. So, it is enough to just update HTTP links to HTTPS.

**Comment by Haqverdi** [comment]
done

**Comment by azizaismayilova** [comment]
Done
