### ISSUE TITLE
Separation of Concerns

### ISSUE THREAD

**Issue by GasimGasimzada** [reactjs/az.reactjs.org#33]
Should it be "Problemleri Ayıraraq" or "Konsernaları Ayıraraq"?

**Comment by Haqverdi** [comment]
In my opinion for a better understanding of the reader should be "Problemleri Ayıraraq"

**Comment by azizaismayilova** [comment]
the second choice is better.

**Comment by Haqverdi** [comment]
> the second choice is better.

it's not very clear, even I hardly understand it myself

**Comment by GasimGasimzada** [comment]
I asked about this in Facebook AZE Dev Group. Here is the post: 
https://www.facebook.com/groups/azeri.developers/permalink/2319479674768875/

**Comment by GasimGasimzada** [comment]
Concern = Öhdəlik according to many devs in the group.
